#!/bin/bash

# Basic configuration
#
dir=$(cd "$(dirname "$0")"; pwd -P)
root=$(dirname $dir)
version=$(grep version.responsio "${root}/build.properties" | egrep -o '[0-9]+(\.[0-9]+)*')

identity_dir="${root}/idents"

identity="prototype"


# Process command line arguments
#
while [[ $# -gt 0 ]]; do
  case "$1" in
    -i | --idents )
      identity_dir="$2"
      shift
      shift
      ;;
    *)
      identity="$1"
      shift
      ;;
  esac
done


echo "Chatting with ${identity}"

# Execute the chat
java -cp "${root}/libs/responsio-${version}.jar:${root}/libs/opennlp-tools-2.1.0.jar:${root}/libs/gson-2.10.jar:." \
    "-Ddir.root=${root}" "-Ddir.identity=${identity_dir}" \
    com.paradoxwebsolutions.tools.Chat "${identity}"
