#!/bin/bash

# Basic configuration
#
dir=$(cd "$(dirname "$0")"; pwd -P)
root=$(dirname $dir)
version=$(grep version.responsio "${root}/build.properties" | egrep -o '[0-9]+(\.[0-9]+)*')

# Check which identity is being trained
#
identity="$1"
if [ -z "$identity" ]
  then
    identity="prototype"
fi
echo "Training ${identity}"


# Configure the input and output directories
#
input_dir="${root}/data/identities"
output_dir="${root}/idents"


# Execute the trainer

java -cp "${root}/libs/responsio-${version}.jar:${root}/libs/opennlp-tools-2.1.0.jar:${root}/libs/gson-2.10.jar:." \
    "-Ddir.root=${root}" "-Ddir.data=${input_dir}" "-Ddir.identity=${output_dir}"\
    com.paradoxwebsolutions.tools.Train "${identity}"
